# See https://pre-commit.com for more information
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-toml
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      args: [--check]
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    - id: clang-format
      args: [--style=file]
-   repo: https://github.com/netromdk/vermin
    rev: 55f159a
    hooks:
      - id: vermin
        args: ['-t=3.7', '--violations']
